 # This is my poweshell workflow yaml file

name: Powershell Test 1 (Osric)
on: [workflow_dispatch]

jobs:
  build:
    name: Run Script
    runs-on: self-hosted, Windows, x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PowerShell script
        shell: powershell
        run: ./mypsscript1.ps1
